### ISSUE TITLE
Create the to do list (200 pts)

### ISSUE THREAD

**Issue by SamuelDunn** [ucsb-cs56-f18/ucsb-cs56-u-to-do#1]
Create the to do list using a java data structure. The user should be able to add dos to the list as text strings.

Link to this side project: https://github.com/ucsb-cs56-f18/ucsb-cs56-f18-u-to-do-side-issue-2.git

Instructions for testing the code is located in the README of this repo.

**Comment by dsegundo2** [comment]
Mentor Approved: 200pts

**Comment by dsegundo2** [comment]
Feature not available on website

**Comment by SamuelDunn** [comment]
This issue was turned in to a side project

**Comment by SamuelDunn** [comment]
Link to the side project repo: https://github.com/ucsb-cs56-f18/ucsb-cs56-f18-u-to-do-side-issue-2.git

Instructions for testing the code is located in the README of this repo.

**Comment by dsegundo2** [comment]
issue completed - it was decided after this was implemented to use a different method for the same functionality so this issue was moved to a side project repo
