### ISSUE TITLE
Display the to-do list on the app's website (create freemarker template) (200 pts)

### ISSUE THREAD

**Issue by SamuelDunn** [ucsb-cs56-f18/ucsb-cs56-u-to-do#8]
Create a Freemarker template that will display the contents of the to-do list.

**Comment by SamuelDunn** [comment]
This issue is no longer needed for the project.

**Comment by dsegundo2** [comment]
issue completed and then it was decided to use a different method for the same functionality so this issue was moved to a side project repo
